# global default
#container:
#  image: gradle:jdk8

# Free BSD
#freebsd_task:
#  freebsd_instance:
#    image_family: freebsd-12-1
#  install_gradle_script:
#    - pkg install -y gradle
#  install_libreoffice_script:
#    - pkg install -y libreoffice
#  build_script:
#    - gradle build

# WINDOWS SHARDS
windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  libreoffice_install_script:
    - choco install -y libreoffice
  dir_script:
    - set
    - dir "C:\"
    - dir "C:\Program Files\"
  matrix:
    - name: java8
      java_install_script:
        - choco install -y jdk8
      gradle_install_script:
        - choco install -y gradle
      build_script:
        - gradlew.bat assemble -x javadoc
      test_script:
        - gradlew.bat check -x integTest

# Avoid build failure caused by the spotless plugin
#init:
#  - git config --global core.autocrlf true

#  # Build artifacts
#  build_script:
#    - gradlew.bat assemble -x javadoc
#
#  # Verify artifacts (without running integration tests)
#  test_script:
#    - gradlew.bat check -x integTest