# Free BSD
#freebsd_task:
#  freebsd_instance:
#    image_family: freebsd-12-1
#  install_gradle_script:
#    - pkg install -y gradle
#  install_libreoffice_script:
#    - pkg install -y libreoffice
#  build_script:
#    - gradle build

# WINDOWS SHARDS
windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  clone_script:
    # Use custom cloning to set the autocrlf to true orelse spotless will fail on Windows
    CMD.exe /C ECHO ON &
      IF NOT DEFINED CIRRUS_PR (
      git config --global core.autocrlf true &
      git clone --recursive --branch=%CIRRUS_BRANCH% https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git %CIRRUS_WORKING_DIR% &
      git reset --hard %CIRRUS_CHANGE_IN_REPO%
    ) ELSE (
      git config --global core.autocrlf true &
      git clone --recursive https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git %CIRRUS_WORKING_DIR% &
      git fetch origin pull/%CIRRUS_PR%/head:pull/%CIRRUS_PR% &
      git reset --hard %CIRRUS_CHANGE_IN_REPO%
    )
  libreoffice_install_script:
    - choco install -y libreoffice
  matrix:
    - name: java8
      env:
        JAVA_HOME: "c:\\java8"
      java_install_script:
        - choco install -y jdk8 -params "installdir=c:\\java8"
      build_script:
        - gradlew.bat build -x javadoc --stacktrace