# LINUX SHARDS
linux_task:
  install_script:
    - apt-get -q update
    - apt-get -y install libreoffice
  # See https://hub.docker.com/_/openjdk for openjdk versions that could be tested.
  matrix:
    - name: linux_java8
      container:
        image: openjdk:8-jdk
    - name: linux_java11
      container:
        image: openjdk:11-jdk
  build_script:
    - ./gradlew build -x javadoc

# WINDOWS SHARDS
windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  clone_script:
    # Use custom cloning to set the autocrlf to true orelse spotless will fail on Windows.
    CMD.exe /C ECHO ON &
      IF NOT DEFINED CIRRUS_PR (
      git config --global core.autocrlf true &
      git clone --recursive --branch=%CIRRUS_BRANCH% https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git %CIRRUS_WORKING_DIR% &
      git reset --hard %CIRRUS_CHANGE_IN_REPO%
    ) ELSE (
      git config --global core.autocrlf true &
      git clone --recursive https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git %CIRRUS_WORKING_DIR% &
      git fetch origin pull/%CIRRUS_PR%/head:pull/%CIRRUS_PR% &
      git reset --hard %CIRRUS_CHANGE_IN_REPO%
    )
  install_libreoffice_script:
    - choco install -y libreoffice
  matrix:
    - name: windows_java8
      env:
        JAVA_HOME: "c:\\java8"
      install_java_script:
        - choco install -y jdk8 -params "installdir=c:\\java8"
    - name: windows_java11
      env:
        JAVA_HOME: "c:\\java11"
      install_java_script:
        - choco install -y jdk11 -params "installdir=c:\\java11"
  build_script:
    - gradlew.bat build -x javadoc

# FREE BSD SHARDS
freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
  #install_gradle_script:
  #  - pkg install -y gradle
  install_libreoffice_script:
    - pkg install -y libreoffice
  # See https://www.freebsd.org/java/ for all available openjdk that could be tested.
  matrix:
      - name: freebsd_java8
        install_java_script:
          - pkg install -y openjdk8
      - name: freebsd_java11
        install_java_script:
          - pkg install -y openjdk11
  build_script:
    - ./gradlew build -x javadoc